require:
  - rubocop-rspec
  - ./spec/support/rubocop_patch

AllCops:
  TargetRubyVersion: 2.6
  Include:
    - 'lib/**/*.rb'
    - 'lib/**/*.thor'
    - 'spec/**/*.rb'
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'Gemfile'

Performance/RedundantBlockCall:
  # Incompatible with documentation/testing requirement of explicitly defining
  # a block argument.
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  # Checks the style of children definitions at classes and modules.
  #
  # Our preferred style is compact-plus-one, which does not match any of the
  # existing styles, so we disable this cop.
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NestedParenthesizedCalls:
  # This cop is excessively strict, especially in cases where the nested method
  # call has only one argument, e.g. outer_method(inner_method arg). Adding the
  # inner parentheses reduces readability.
  Enabled: false

Style/SingleLineBlockParams:
  # Prefer descriptive block param names.
  Enabled: false

Style/TrailingUnderscoreVariable:
  # Prefer more explicit syntax when ignoring destructured results.
  Enabled: false

### TEMPORARILY DISABLED COPS

# These should be applied to new code and to code that has been reformatted to
# updated standards.

Layout/AlignHash:
  Enabled: false

Layout/DotPosition:
  # Disabled while transitioning to modern syntax.
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/BigDecimalNew:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/HooksBeforeExamples:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/EmptyLambdaParameter:
  Enabled: false

Style/FrozenStringLiteralComment:
  # Incompatible with file location comments.
  Enabled: false

Style/HashSyntax:
  # Disabled while transitioning to modern syntax.
  Enabled: false

Style/MethodDefParentheses:
  # Disabled while transitioning to modern syntax.
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'spec/**/*.rb'

Style/NumericPredicate:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
