# .travis.yml

# Build Options
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
before_script:
  - cp .rspec.example .rspec
script:
  - bundle exec thor bronze:ci:default

# Travis-CI Configuration
cache: bundler
sudo:  false # Enable containerized builds.
