# .travis.yml

# Build Options
language: ruby
rvm:
- 2.3.1
before_script:
- cp .rspec.example .rspec
script:
- bundle exec thor bronze:ci:default

# Travis-CI Configuration
cache: bundler
sudo:  false # Enable containerized builds.
